use std::{env, fs, io, path::Path, process::Command};

fn main() {
    println!("cargo:rerun-if-changed=ui/pill.ts");
    println!("cargo:rerun-if-changed=ui/pill.css");
    println!("cargo:rerun-if-changed=ui/index.html");
    println!("cargo:rerun-if-changed=ui/textbox.ts");
    println!("cargo:rerun-if-changed=ui/textbox.css");
    println!("cargo:rerun-if-changed=ui/textbox.html");
    println!("cargo:rerun-if-changed=ui/hud.ts");
    println!("cargo:rerun-if-changed=ui/hud.css");
    println!("cargo:rerun-if-changed=ui/hud.html");
    println!("cargo:rerun-if-changed=ui/orb-engine.js");
    println!("cargo:rerun-if-changed=ui/orb-engine.d.ts");
    println!("cargo:rerun-if-changed=ui/tauri.d.ts");
    println!("cargo:rerun-if-changed=ui/tsconfig.json");
    println!("cargo:rerun-if-changed=shell");
    println!("cargo:rerun-if-changed=../widgets");
    println!("cargo:rerun-if-changed=../backends");
    build_frontend();
    build_widgets();
    build_backends();
    tauri_build::build();
}

/// Compiles the frontend scripts and assembles the complete frontend in
/// ui/dist, the directory tauri.conf.json embeds. A frontend that does not
/// compile fails the build; there is no shipping the pill without its script.
fn build_frontend() {
    let ui = Path::new("ui");
    let status = tsc(&ui.join("tsconfig.json"))
        .expect("tsc is required to build the pill frontend and was not found");
    assert!(status.success(), "tsc failed on the pill frontend");
    for file in [
        "index.html",
        "pill.css",
        "textbox.html",
        "textbox.css",
        "hud.html",
        "hud.css",
        "orb-engine.js",
    ] {
        fs::copy(ui.join(file), ui.join("dist").join(file))
            .unwrap_or_else(|error| panic!("could not copy ui/{file} into ui/dist: {error}"));
    }
    // The widget shell is its own tsc project: it is a page of its own, with a
    // contract of its own, and one project that compiled both would let a name
    // from the pill leak into it.
    let shell = Path::new("shell");
    let status = tsc(&shell.join("tsconfig.json")).expect("tsc was not found");
    assert!(status.success(), "tsc failed on the widget shell");
    for file in ["shell.html", "shell.css", "tokens.css"] {
        fs::copy(shell.join(file), ui.join("dist").join(file))
            .unwrap_or_else(|error| panic!("could not copy shell/{file} into ui/dist: {error}"));
    }
}

/// Compiles every widget under native/widgets and writes the table the
/// catalog reads.
///
/// The table holds each widget's manifest and its compiled module, so what the
/// companion can open is exactly what was built. A widget whose TypeScript does
/// not compile fails the build rather than the first person who asks for it.
///
/// One module per widget, embedded whole, and that is the constraint behind the
/// duplication between them: a widget is delivered as one text with no
/// directory behind it, so an import of a shared file has nothing to resolve
/// against and would fail in the surface rather than here. Two widgets that
/// want the same code copy it. A shared prelude concatenated in below is
/// possible and is not what is built - until it is, the copies are the price.
fn build_widgets() {
    let widgets = Path::new("..").join("widgets");
    let status = tsc(&widgets.join("tsconfig.json")).expect("tsc was not found");
    assert!(status.success(), "tsc failed on the widgets");

    let mut directories: Vec<String> = fs::read_dir(&widgets)
        .expect("native/widgets is missing")
        .filter_map(|entry| {
            let entry = entry.expect("native/widgets could not be read");
            entry
                .path()
                .join("widget.toml")
                .is_file()
                .then(|| entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    // Sorted so the generated table - and with it the catalog the agent is
    // told about - does not depend on the order the filesystem hands back.
    directories.sort();
    assert!(!directories.is_empty(), "no widget has a widget.toml");

    let root = env::current_dir().expect("the build has a working directory");
    let mut table = String::from(
        "// Generated by build.rs from native/widgets. Do not edit.\n\
         pub const INSTALLED: &[Source<'static>] = &[\n",
    );
    for directory in directories {
        let manifest = root.join("../widgets").join(&directory).join("widget.toml");
        // Outside ui/dist on purpose. Everything under the frontend directory
        // is bundled into the app protocol and reachable from any window, and
        // a widget module served from there would make the per-surface
        // scufris-widget: scheme a formality rather than a gate.
        let script = root
            .join("../widgets/dist")
            .join(&directory)
            .join("widget.js");
        assert!(
            script.is_file(),
            "widgets/{directory} has a manifest but compiled no widget.js"
        );
        table.push_str(&format!(
            "    Source {{\n        directory: {directory:?},\n        manifest: include_str!({:?}),\n        script: include_str!({:?}),\n    }},\n",
            manifest.display().to_string(),
            script.display().to_string(),
        ));
    }
    table.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("widgets.rs");
    fs::write(&out, table).unwrap_or_else(|error| {
        panic!(
            "could not write the widget table to {}: {error}",
            out.display()
        )
    });
}

/// Writes the table of backends the supervisor starts.
///
/// A backend is a directory under `native/backends/` holding `backend.py`, and
/// the directory name is the backend's identifier. The program text is compiled
/// in rather than installed beside the binary: a backend that shipped as a file
/// on disk would be a file that can go missing, be edited, or disagree with the
/// widget that names it.
///
/// The same constraint as the widgets, and the same consequence. One file is
/// the whole backend, so `deaf()` and the driver around it are copied between
/// them rather than imported from one place.
fn build_backends() {
    let backends = Path::new("..").join("backends");
    let mut directories: Vec<String> = fs::read_dir(&backends)
        .expect("native/backends is missing")
        .filter_map(|entry| {
            let entry = entry.expect("native/backends could not be read");
            entry
                .path()
                .join("backend.py")
                .is_file()
                .then(|| entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    // Sorted for the reason the widget table is: what is generated must not
    // depend on the order the filesystem hands directories back.
    directories.sort();
    assert!(!directories.is_empty(), "no backend has a backend.py");

    let root = env::current_dir().expect("the build has a working directory");
    let mut table = String::from(
        "// Generated by build.rs from native/backends. Do not edit.\n\
         const INSTALLED: &[Backend<'static>] = &[\n",
    );
    for directory in directories {
        let script = root.join("../backends").join(&directory).join("backend.py");
        table.push_str(&format!(
            "    Backend {{\n        id: {directory:?},\n        script: include_str!({:?}),\n    }},\n",
            script.display().to_string(),
        ));
    }
    table.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("backends.rs");
    fs::write(&out, table).unwrap_or_else(|error| {
        panic!(
            "could not write the backend table to {}: {error}",
            out.display()
        )
    });
}

/// Runs the compiler from PATH, or through npx from the repository checkout
/// when the shell does not carry tsc itself.
fn tsc(project: &Path) -> io::Result<std::process::ExitStatus> {
    match Command::new("tsc").arg("-p").arg(project).status() {
        Err(error) if error.kind() == io::ErrorKind::NotFound => Command::new("npx")
            .args(["--no-install", "tsc", "-p"])
            .arg(project)
            .status(),
        outcome => outcome,
    }
}
