//! The Scufris service.
//!
//! It owns three things nothing else may own: the `pi --mode rpc` agent, the
//! session directory that agent writes, and the socket every surface connects
//! to. Everything else - the pill, the tray, a terminal, `scufris-ctl` - is a
//! client of this process.
//!
//! What to run and where the sessions live come from the environment, because
//! the unit that starts it is generated by the Home Manager module and that
//! module already knows the store paths. The same two are options as well, so
//! the service can be pointed somewhere else for one run from a terminal.
//!
//! Shutting down is deliberate rather than abrupt. `SIGINT` and `SIGTERM` are
//! blocked before any thread exists and then waited for on the main thread, so
//! the agent is stopped and the socket is removed before the process goes.
//! Without that, a service stopped by hand leaves an orphaned agent holding
//! the session, and the next start finds a conversation with two writers.

mod agent;
mod config;
mod logging;
mod rpc;
mod server;
mod service;

use std::{path::PathBuf, process::ExitCode, sync::Arc, thread};

use clap::Parser;
use nix::sys::signal::{SigSet, Signal};
use tracing::{error, info};

use crate::{config::Config, service::Service};

/// What a failing exit means.
const FAILED: u8 = 1;

/// One run of the service.
#[derive(Debug, Parser)]
#[command(
    name = "scufris-service",
    version,
    about = "The Scufris background service",
    long_about = "Owns one `pi --mode rpc` agent, its session directory, and the socket \
                  every Scufris surface connects to. Talk to it with scufris-ctl.\n\n\
                  The socket goes under XDG_RUNTIME_DIR, and RUST_LOG sets the log \
                  directives."
)]
struct Options {
    /// Absolute path of the agent to run.
    ///
    /// With none given, the first `scufris` on PATH.
    #[arg(long, env = config::AGENT_VARIABLE, value_name = "PATH")]
    agent: Option<PathBuf>,

    /// Absolute path of the directory the session is kept in.
    ///
    /// With none given, `scufris/sessions` under the user's data directory.
    #[arg(long, env = config::SESSION_DIR_VARIABLE, value_name = "PATH")]
    session_dir: Option<PathBuf>,
}

fn main() -> ExitCode {
    let options = Options::parse();

    // Before any thread exists, so every thread inherits the block and the
    // wait below is the only place either signal is delivered.
    let mut stopping = SigSet::empty();
    stopping.add(Signal::SIGINT);
    stopping.add(Signal::SIGTERM);
    if let Err(error) = stopping.thread_block() {
        eprintln!("scufris-service: signals could not be blocked: {error}");
        return ExitCode::from(FAILED);
    }

    if let Err(error) = logging::init() {
        eprintln!("scufris-service: {error}");
        return ExitCode::from(FAILED);
    }

    let named = |path: Option<PathBuf>| path.map(PathBuf::into_os_string);
    let config = match Config::from_environment(named(options.agent), named(options.session_dir)) {
        Ok(config) => config,
        Err(error) => {
            error!(%error, "the service is not configured");
            return ExitCode::from(FAILED);
        }
    };
    let paths = [
        (config.surface_socket.clone(), server::Channel::Surface),
        (config.agent_socket.clone(), server::Channel::Agent),
        (config.control_socket.clone(), server::Channel::Control),
    ];
    let mut listeners = Vec::new();
    for (path, channel) in &paths {
        match server::bind(path) {
            Ok(listener) => listeners.push((listener, *channel)),
            Err(error) => {
                error!(%error, socket = %path.display(), "a socket would not bind");
                return ExitCode::from(FAILED);
            }
        }
    }
    info!(
        surface = %config.surface_socket.display(),
        agent = %config.agent_socket.display(),
        control = %config.control_socket.display(),
        sessions = %config.session_dir.display(),
        "the service is listening"
    );

    let service = Service::new(config);
    service.start_agent();

    for (listener, channel) in listeners {
        let serving = Arc::clone(&service);
        if let Err(error) = thread::Builder::new()
            .name(format!("scufris-{}-accept", channel.name()))
            .spawn(move || server::serve(serving, listener, channel))
        {
            error!(%error, "an accept thread would not start");
            return ExitCode::from(FAILED);
        }
    }

    match stopping.wait() {
        Ok(signal) => info!(?signal, "the service is stopping"),
        Err(error) => error!(%error, "the signal wait failed, stopping anyway"),
    }
    service.shutdown();
    // Last, so nothing connects to sockets whose service has let go of Pi.
    for (socket, _) in paths {
        if let Err(error) = std::fs::remove_file(&socket) {
            error!(%error, socket = %socket.display(), "a socket could not be removed");
        }
    }
    ExitCode::SUCCESS
}
